### ISSUE TITLE
Firefox address bar at bottom

### ISSUE THREAD

**Issue by drazde** [jonhoo/configs#6]
Hi, 
Seems that with FF 72.0b2 it has broaken...

**Comment by jonhoo** [comment]
Hmm, I'm on 71.0b12 and it seems to work just fine. Are you sure you're using the latest version? I remember having to make edits to it recently, so it might be that you need a _newer_ version for the style to work correctly now. Alternatively you could just check out the old config in the gist history :)

**Comment by drazde** [comment]
Yes, I get `userChrome.css` a year ago, 
but today I have update it with the latest

I also use the latest version of FF developer edition

**Comment by jonhoo** [comment]
Ah, sorry, you're right, I just hadn't updated my FF dev edition! Will take a look and push a fix.

**Comment by drazde** [comment]
Yeah thanks, 
I had try to fix it myself but I was not successful..  :(

**Comment by alexschrod** [comment]
I realize this is not the Firefox userChrome help desk, but since I got the CSS to place my address bar on the bottom from here, I figured I'd just ask. Everything looks fine when browsing, but when activating the address bar, the "search suggestions" drop down kind of... sits in a very awkward position, as you can see in this screenshot:
![image](https://user-images.githubusercontent.com/767490/195793074-c78f84f9-e62c-4df6-9baf-303f7ba6e3a7.png)
Any suggestions on what to do about it? 🙂
